export const AUTH_START = 'AUTH_START';
export const AUTH_END = 'AUTH_END';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const VERIFICATION_EMAIL_START = 'VERIFICATION_EMAIL_START';
export const VERIFICATION_EMAIL_SUCCESS = 'VERIFICATION_EMAIL_SUCCESS';
export const VERIFICATION_EMAIL_FAIL = 'VERIFICATION_EMAIL_FAIL';

export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL';
